export const CATEGORIE_KLEUREN = {
  "Basisconcepten":    "#2C5A85",
  "Tools & Modellen":  "#7C3AED",
  "Prompting":         "#059669",
  "Praktisch gebruik": "#D97706",
  "Veiligheid":        "#DC2626",
};

export const termen = [
  // ── Basisconcepten ──────────────────────────────────────────────
  {
    term: "Kunstmatige intelligentie",
    categorie: "Basisconcepten",
    definitie: "Software die taken uitvoert waarvoor normaal menselijk denken nodig is, zoals tekst schrijven, vragen beantwoorden of afbeeldingen herkennen.",
    voorbeeld: "Je vraagt ChatGPT om een klachtbrief te schrijven. Dat is kunstmatige intelligentie aan het werk.",
  },
  {
    term: "Machine learning",
    categorie: "Basisconcepten",
    definitie: "Een manier om AI te trainen door het duizenden voorbeelden te tonen, zodat het zelf patronen leert herkennen. De AI krijgt geen regels maar voorbeelden.",
    voorbeeld: "ChatGPT heeft miljoenen teksten gelezen en geleerd hoe goede Nederlandse zinnen eruitzien.",
  },
  {
    term: "Taalmodel (LLM)",
    categorie: "Basisconcepten",
    definitie: "Een AI die gespecialiseerd is in taal. Het kan tekst lezen, begrijpen en schrijven. LLM staat voor Large Language Model.",
    voorbeeld: "ChatGPT, Claude en Gemini zijn alle drie taalmodellen.",
  },
  {
    term: "Generatieve AI",
    categorie: "Basisconcepten",
    definitie: "AI die nieuwe inhoud maakt, zoals tekst, afbeeldingen, muziek of video. Het genereert iets wat er nog niet was.",
    voorbeeld: "Je vraagt DALL-E om een foto van een kat op de maan. Dat is generatieve AI.",
  },
  {
    term: "Algoritme",
    categorie: "Basisconcepten",
    definitie: "Een reeks stappen die een computer volgt om een probleem op te lossen. Vergelijk het met een recept: stap voor stap naar het resultaat.",
    voorbeeld: "Het algoritme van Instagram bepaalt welke posts jij als eerste ziet.",
  },
  {
    term: "Neuraal netwerk",
    categorie: "Basisconcepten",
    definitie: "Het systeem waarmee AI leert, geïnspireerd op de werking van het menselijk brein. Bestaat uit lagen van verbonden knooppunten die informatie doorgeven.",
    voorbeeld: "Een neuraal netwerk herkent of een foto een hond of een kat bevat door patronen te vergelijken.",
  },
  {
    term: "Trainingsdata",
    categorie: "Basisconcepten",
    definitie: "De verzameling teksten, afbeeldingen of andere informatie waarop een AI is getraind. Hoe meer en betere data, hoe capabeler de AI.",
    voorbeeld: "ChatGPT is getraind op een groot deel van het internet, waaronder boeken, Wikipedia en websites.",
  },
  {
    term: "Hallucinatie",
    categorie: "Basisconcepten",
    definitie: "Wanneer een AI iets verzint dat niet klopt maar het zelfverzekerd presenteert als feit. De AI liegt niet bewust maar gist verkeerd.",
    voorbeeld: "Je vraagt ChatGPT naar een wetenschappelijk artikel. Het noemt een titel, auteur en tijdschrift die allemaal niet bestaan.",
  },
  {
    term: "Context",
    categorie: "Basisconcepten",
    definitie: "De informatie die je meegeeft in een gesprek met AI. Hoe meer relevante context je geeft, hoe beter het antwoord.",
    voorbeeld: "\"Schrijf een e-mail\" geeft weinig context. \"Schrijf een formele e-mail aan mijn verhuurder over een lekkage die al twee weken niet is opgelost\" geeft veel context.",
  },
  {
    term: "Token",
    categorie: "Basisconcepten",
    definitie: "De kleinste eenheid waarmee een AI tekst verwerkt. Ruwweg één woord of een deel van een woord. AI-modellen hebben een limiet op het aantal tokens per gesprek.",
    voorbeeld: "De zin \"Ik gebruik ChatGPT dagelijks\" bevat ongeveer zes tokens.",
  },

  // ── Tools & Modellen ────────────────────────────────────────────
  {
    term: "ChatGPT",
    categorie: "Tools & Modellen",
    definitie: "De bekendste AI-chatbot ter wereld, gemaakt door het Amerikaanse bedrijf OpenAI. Je typt een vraag of opdracht en ChatGPT antwoordt in gewone taal.",
    voorbeeld: "Je plakt je cv erin en vraagt ChatGPT om het te verbeteren voor een specifieke vacature.",
    fixSlug: "chatgpt-voor-beginners",
    fixTitel: "ChatGPT gebruiken voor beginners",
  },
  {
    term: "Claude",
    categorie: "Tools & Modellen",
    definitie: "Een AI-assistent van Anthropic, een Amerikaans bedrijf gericht op veilige AI. Bekend om genuanceerde en doordachte antwoorden, vooral bij schrijftaken.",
    voorbeeld: "Je vraagt Claude om feedback op een gevoelige e-mail. Het geeft uitgebreide toelichting bij zijn suggesties.",
    fixSlug: "claude-ai-gebruiken-nederlands",
    fixTitel: "Claude AI gebruiken in het Nederlands",
  },
  {
    term: "Gemini",
    categorie: "Tools & Modellen",
    definitie: "De AI van Google, ingebouwd in Gmail, Google Docs en Google Zoeken. Voor mensen die al met Google werken de meest toegankelijke AI.",
    voorbeeld: "Je werkt in Google Docs en klikt op het Gemini-knopje om een alinea te laten herschrijven.",
    fixSlug: "gemini-google-gebruiken-nederlands",
    fixTitel: "Gemini van Google gebruiken",
  },
  {
    term: "GPT-4o",
    categorie: "Tools & Modellen",
    definitie: "Het krachtigste model van OpenAI, beschikbaar in ChatGPT. Kan tekst, afbeeldingen en geluid verwerken in één gesprek.",
    voorbeeld: "Je stuurt een foto van een contract naar GPT-4o en vraagt wat er in staat.",
  },
  {
    term: "Copilot",
    categorie: "Tools & Modellen",
    definitie: "De AI-assistent van Microsoft, geïntegreerd in Windows, Word, Excel en Outlook. Toegankelijk via je Microsoft-account.",
    voorbeeld: "Je opent Word, klikt op Copilot en vraagt het om een vergaderverslag samen te vatten.",
  },
  {
    term: "DALL-E",
    categorie: "Tools & Modellen",
    definitie: "Een AI van OpenAI die afbeeldingen genereert op basis van een tekstomschrijving. Beschikbaar via ChatGPT.",
    voorbeeld: "Je typt \"een gezellige woonkamer in Scandinavische stijl\" en DALL-E genereert er een afbeelding van.",
  },
  {
    term: "Midjourney",
    categorie: "Tools & Modellen",
    definitie: "Een populaire AI voor het genereren van artistieke en realistische afbeeldingen. Staat bekend om visueel hoogwaardige resultaten.",
    voorbeeld: "Ontwerpers gebruiken Midjourney om snel moodboards te maken voor klanten.",
  },
  {
    term: "Perplexity",
    categorie: "Tools & Modellen",
    definitie: "Een AI-zoekmachine die vragen beantwoordt en direct de bronnen vermeldt. Handiger dan Google voor complexe vragen.",
    voorbeeld: "Je vraagt \"wat zijn de regels voor zzp'ers en BTW in 2025\" en Perplexity geeft een overzicht met links naar officiële bronnen.",
  },
  {
    term: "NotebookLM",
    categorie: "Tools & Modellen",
    definitie: "Een gratis Google-tool waarmee je je eigen documenten uploadt en er vragen over kunt stellen. Ideaal voor grote hoeveelheden tekst.",
    voorbeeld: "Je upload een jaarverslag en vraagt NotebookLM om de drie belangrijkste risico's samen te vatten.",
  },
  {
    term: "API",
    categorie: "Tools & Modellen",
    definitie: "Een technische verbinding waarmee twee applicaties met elkaar communiceren. Voor AI: de manier om een AI-model in een eigen app of workflow te integreren.",
    voorbeeld: "Ontwikkelaars gebruiken de OpenAI API om ChatGPT in hun eigen software in te bouwen.",
  },

  // ── Prompting ───────────────────────────────────────────────────
  {
    term: "Prompt",
    categorie: "Prompting",
    definitie: "De tekst die jij typt om AI een opdracht te geven. De kwaliteit van je prompt bepaalt grotendeels de kwaliteit van het antwoord.",
    voorbeeld: "\"Schrijf iets over e-mail\" is een slechte prompt. \"Schrijf een korte herinnering aan een collega die een vergadering heeft gemist, met de drie actiepunten\" is een goede prompt.",
    fixSlug: "ai-prompts-schrijven",
    fixTitel: "ChatGPT prompts schrijven die werken",
  },
  {
    term: "Prompt engineering",
    categorie: "Prompting",
    definitie: "De vaardigheid van het schrijven van effectieve prompts. Geen programmeerkennis nodig, wel oefening en inzicht.",
    voorbeeld: "Je leert dat het helpt om AI een rol te geven (\"Jij bent een ervaren recruiter...\") voordat je een vraag stelt.",
    fixSlug: "ai-prompts-schrijven",
    fixTitel: "ChatGPT prompts schrijven die werken",
  },
  {
    term: "Systeemprompt",
    categorie: "Prompting",
    definitie: "Een instructie die je aan het begin van een gesprek geeft om het gedrag van AI voor het hele gesprek te bepalen.",
    voorbeeld: "\"Geef al je antwoorden in simpel Nederlands, zonder vakjargon. Mijn moeder van 70 leest dit mee.\"",
  },
  {
    term: "Rol geven",
    categorie: "Prompting",
    definitie: "AI vertellen wie het moet zijn voordat je een vraag stelt. Dit geeft de output een specifieke toon, stijl of expertise.",
    voorbeeld: "\"Jij bent een ervaren huurrechtadvocaat. Beoordeel dit huurcontract vanuit het oogpunt van de huurder.\"",
    fixSlug: "huurcontract-checken",
    fixTitel: "Huurcontract controleren met ChatGPT",
  },
  {
    term: "Context meegeven",
    categorie: "Prompting",
    definitie: "Relevante achtergrond toevoegen aan je prompt zodat AI beter begrijpt wat je nodig hebt en waarom.",
    voorbeeld: "In plaats van \"schrijf een sollicitatiebrief\" geef je mee: de vacature, je werkervaring en de reden waarom je van baan wilt wisselen.",
    fixSlug: "cv-en-sollicitatiebrief",
    fixTitel: "Sollicitatiebrief schrijven met ChatGPT",
  },
  {
    term: "Voorbeelden geven",
    categorie: "Prompting",
    definitie: "Concrete voorbeelden toevoegen aan je prompt om AI te laten zien wat je bedoelt. Werkt beter dan lange beschrijvingen.",
    voorbeeld: "\"Schrijf titels in de stijl van deze voorbeelden: [voorbeeld 1], [voorbeeld 2], [voorbeeld 3].\"",
  },
  {
    term: "Itereren",
    categorie: "Prompting",
    definitie: "Je prompt aanpassen op basis van het antwoord dat AI geeft, totdat je krijgt wat je nodig hebt. AI werkt het best als je het bijstuurt.",
    voorbeeld: "AI geeft een te formele e-mail. Je reageert: \"Maak het informeler, alsof ik het aan een bekende collega schrijf.\"",
  },
  {
    term: "Temperatuur",
    categorie: "Prompting",
    definitie: "Een instelling die bepaalt hoe creatief of voorspelbaar de AI reageert. Hogere temperatuur is creatiever, lagere temperatuur is consistenter.",
    voorbeeld: "Voor een zakelijke samenvatting wil je lage temperatuur. Voor brainstormen over campagne-ideeën wil je hogere temperatuur.",
  },
  {
    term: "Contextvenster",
    categorie: "Prompting",
    definitie: "De maximale hoeveelheid tekst die een AI in één keer kan verwerken en onthouden. Vergelijk het met het werkgeheugen van een mens.",
    voorbeeld: "Je plakt een heel boek in ChatGPT maar het kan alleen de laatste hoofdstukken goed verwerken vanwege het beperkte contextvenster.",
  },
  {
    term: "Output",
    categorie: "Prompting",
    definitie: "Het antwoord of resultaat dat AI produceert op jouw prompt. Controleer output altijd op fouten of onnauwkeurigheden.",
    voorbeeld: "Je vraagt om een samenvatting. De samenvatting die AI teruggeeft is de output.",
  },

  // ── Praktisch gebruik ───────────────────────────────────────────
  {
    term: "AI-assistent",
    categorie: "Praktisch gebruik",
    definitie: "Een AI-tool die je helpt bij dagelijkse taken via een gespreksvorm. ChatGPT, Claude en Gemini zijn voorbeelden.",
    voorbeeld: "Je vraagt je AI-assistent om je agenda van morgen samen te vatten en de drie prioriteiten te benoemen.",
    fixSlug: "ai-voor-beginners",
    fixTitel: "AI voor beginners: de complete startgids",
  },
  {
    term: "Automatisering",
    categorie: "Praktisch gebruik",
    definitie: "Het laten uitvoeren van herhaalde taken door software, zodat jij er geen tijd aan hoeft te besteden.",
    voorbeeld: "In plaats van elke week handmatig je budgetoverzicht bij te werken, geef je de cijfers aan ChatGPT en laat je het overzicht genereren.",
    fixSlug: "financieel-maandoverzicht",
    fixTitel: "Financieel overzicht maken met ChatGPT",
  },
  {
    term: "Workflow",
    categorie: "Praktisch gebruik",
    definitie: "Een reeks stappen die je regelmatig doorloopt om een taak af te ronden. AI kan helpen om die stappen te versnellen of over te nemen.",
    voorbeeld: "Je workflow voor rapporten: onderzoek, outline, schrijven, revisie. AI kan elke stap ondersteunen.",
  },
  {
    term: "AI-agent",
    categorie: "Praktisch gebruik",
    definitie: "AI die zelfstandig meerdere stappen achter elkaar uitvoert om een doel te bereiken, zonder dat jij elke stap hoeft aan te sturen.",
    voorbeeld: "Je geeft een AI-agent de opdracht om vluchten te zoeken, prijzen te vergelijken en de beste optie te selecteren. Het doet alles zelf.",
  },
  {
    term: "Samenvatten",
    categorie: "Praktisch gebruik",
    definitie: "Een lange tekst inkorten tot de kern, zodat je de belangrijkste informatie behoudt zonder alles te hoeven lezen.",
    voorbeeld: "Je plakt een vergaderverslag van drie pagina's in ChatGPT en vraagt om een samenvatting van vijf actiepunten.",
    fixSlug: "vergadering-samenvatten",
    fixTitel: "Vergadernotities samenvatten met ChatGPT",
  },
  {
    term: "Transcriptie",
    categorie: "Praktisch gebruik",
    definitie: "Gesproken woord omzetten naar geschreven tekst. AI kan dit automatisch doen van opnames of live gesprekken.",
    voorbeeld: "Je neemt een vergadering op en laat AI de transcriptie maken. Vervolgens vraag je om een samenvatting van de actiepunten.",
    fixSlug: "vergadering-samenvatten",
    fixTitel: "Vergadernotities samenvatten met ChatGPT",
  },
  {
    term: "Multimodaal",
    categorie: "Praktisch gebruik",
    definitie: "AI die meerdere soorten informatie tegelijk kan verwerken, zoals tekst, afbeeldingen, geluid en video.",
    voorbeeld: "Je stuurt een foto van een beschadigde fiets naar GPT-4o en vraagt wat er kapot is en wat de reparatie kost.",
  },
  {
    term: "Integratie",
    categorie: "Praktisch gebruik",
    definitie: "AI koppelen aan apps en tools die je al gebruikt, zodat je er direct in kunt werken zonder te wisselen van programma.",
    voorbeeld: "Gemini is geïntegreerd in Gmail, zodat je e-mails kunt samenvatten of schrijven zonder een ander tabblad te openen.",
    fixSlug: "gemini-google-gebruiken-nederlands",
    fixTitel: "Gemini van Google gebruiken",
  },
  {
    term: "No-code AI",
    categorie: "Praktisch gebruik",
    definitie: "AI-tools gebruiken zonder te hoeven programmeren. Bedoeld voor iedereen, niet alleen voor ontwikkelaars.",
    voorbeeld: "Je bouwt een chatbot voor je website via een no-code tool, zonder één regel code te schrijven.",
  },
  {
    term: "Voice AI",
    categorie: "Praktisch gebruik",
    definitie: "AI die instructies via spraak ontvangt en antwoordt met gesproken tekst. De spraakfunctie van ChatGPT is een bekend voorbeeld.",
    voorbeeld: "Je rijdt in de auto en vraagt via de ChatGPT-app hardop om de vergadering van morgen voor te bereiden.",
    fixSlug: "vergadering-voorbereiden",
    fixTitel: "Vergadering voorbereiden met ChatGPT",
  },

  // ── Veiligheid & Ethiek ─────────────────────────────────────────
  {
    term: "Bias",
    categorie: "Veiligheid",
    definitie: "Vooringenomenheid in AI-output die ontstaat doordat de trainingsdata niet representatief was. AI neemt bestaande ongelijkheid soms over.",
    voorbeeld: "Een AI die sollicitanten beoordeelt, keert zich vaker af tegen vrouwen als het is getraind op historische data waar voornamelijk mannen werden aangenomen.",
  },
  {
    term: "Deepfake",
    categorie: "Veiligheid",
    definitie: "Een nep-video, foto of audiofragment gemaakt met AI, waarbij iemand iets lijkt te zeggen of doen wat nooit is gebeurd.",
    voorbeeld: "Een video van een CEO die zijn ontslag aankondigt, terwijl hij dat nooit heeft gezegd. Gemaakt met AI.",
  },
  {
    term: "Privacyrisico",
    categorie: "Veiligheid",
    definitie: "Het gevaar dat gevoelige informatie die je in AI-tools invoert, wordt opgeslagen of gebruikt voor verdere training.",
    voorbeeld: "Je plakt het contract van een klant in ChatGPT. Dat contract bevat vertrouwelijke informatie die je eigenlijk niet mag delen.",
  },
  {
    term: "Auteursrecht en AI",
    categorie: "Veiligheid",
    definitie: "De juridisch nog onopgeloste vraag over wie eigenaar is van door AI gegenereerde inhoud en of AI mag worden getraind op beschermd materiaal.",
    voorbeeld: "Je laat AI een logo ontwerpen. Of jij dat logo juridisch bezit of mag gebruiken is niet overal even duidelijk.",
  },
  {
    term: "GDPR en AI",
    categorie: "Veiligheid",
    definitie: "De Europese privacywet stelt eisen aan hoe AI-systemen omgaan met persoonsgegevens van Europeanen.",
    voorbeeld: "Een bedrijf mag niet zomaar klantgegevens invoeren in een extern AI-systeem zonder na te gaan of dat GDPR-conform is.",
  },
  {
    term: "Jailbreaking",
    categorie: "Veiligheid",
    definitie: "Het proberen om AI via slimme formuleringen te omzeilen, zodat het toch doet wat het normaal weigert.",
    voorbeeld: "Iemand vraagt ChatGPT om \"als fictief personage\" instructies te geven die het normaal zou weigeren.",
  },
  {
    term: "Verantwoorde AI",
    categorie: "Veiligheid",
    definitie: "AI gebruiken op een manier die eerlijk, transparant en veilig is, met oog voor de impact op anderen.",
    voorbeeld: "Vermeld altijd dat een tekst door AI is geschreven als dat relevant is voor de lezer.",
  },
  {
    term: "Fact-checking",
    categorie: "Veiligheid",
    definitie: "Het controleren van AI-output op juistheid. Altijd nodig, want AI maakt fouten en verzint soms informatie.",
    voorbeeld: "ChatGPT noemt een statistiek over werkloosheid. Je zoekt de bron op voordat je het gebruikt in een presentatie.",
  },
  {
    term: "Digitale geletterdheid",
    categorie: "Veiligheid",
    definitie: "De vaardigheid om AI en digitale tools kritisch en effectief te gebruiken. Weten wat AI wel en niet kan.",
    voorbeeld: "Iemand die begrijpt dat AI-output altijd gecontroleerd moet worden, is digitaal geletterd.",
  },
  {
    term: "Menselijk toezicht",
    categorie: "Veiligheid",
    definitie: "De afspraak dat een mens altijd de uiteindelijke beslissing neemt, ook als AI een aanbeveling doet.",
    voorbeeld: "AI stelt een ontslagbrief op, maar een HR-manager controleert en beslist altijd zelf of die brief verstuurd wordt.",
  },
];
